######################## Filebeat Configuration ############################

#=========================== Filebeat prospectors =============================

filebeat.prospectors:

- type: log
  paths:
    - /var/log/php_app/access.log
    - /var/log/php_app/error.log
  fields:
    log_type: apache
  fields_under_root: true

#========================= Filebeat global options ============================

filebeat.registry_file: /var/lib/filebeat/registry

#================================ Outputs ======================================

#----------------------------- Logstash output ---------------------------------
output.logstash:
  hosts: ["logstash:5044"]
